# Generated by Django 5.0 on 2024-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('saldo', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('numeroTelefono', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('ifLogged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('saldo', models.BigIntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('numeroTelefono', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('ifLogged', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
