# Generated by Django 5.0 on 2024-05-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numeroTelefono', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('ifLogged', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
