# Generated by Django 5.0 on 2025-07-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlibrary',
            managers=[
            ],
        ),
    ]
