# Generated by Django 5.0 on 2025-07-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userlibrary_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={},
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
