# Generated by Django 5.0 on 2025-07-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userlibrary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='tel',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
