# Generated by Django 5.0 on 2025-07-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userlibrary_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
