# Generated by Django 5.0 on 2024-05-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=20)),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
