# Generated by Django 5.0 on 2024-05-26 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroAdmin',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=20)),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('userAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useradmin')),
            ],
            options={
                'verbose_name_plural': 'Libro',
            },
        ),
        migrations.CreateModel(
            name='LibroUser',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=20)),
                ('librosComprados', models.IntegerField()),
                ('userAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Libro',
            },
        ),
        migrations.CreateModel(
            name='Transacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transaccion', models.CharField(max_length=15)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_ejemplares', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libroadmin')),
            ],
            options={
                'verbose_name_plural': 'Transaccion',
            },
        ),
    ]
