# Generated by Django 5.0 on 2024-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroUser',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=20)),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='user',
        ),
    ]
