# Generated by Django 5.0 on 2024-05-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libroadmin_useradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libroadmin',
            options={'verbose_name_plural': 'LibroAdmin'},
        ),
    ]
