# Generated by Django 5.0 on 2024-05-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libroadmin_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librouser',
            old_name='userAdmin',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='librouser',
            name='librosComprados',
            field=models.IntegerField(default=0),
        ),
    ]
